
'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("a1cde6fa-65c0-485b-ad47-1a0cfd25bf81")>
#Region "Métadonnées de relation EDM"
<Assembly: EdmRelationshipAttribute("Model", "groupesinscription", "groupes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.groupes), "inscription", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.inscription))>
<Assembly: EdmRelationshipAttribute("Model", "paiementsinscription", "paiements", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.paiements), "inscription", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.inscription))>
<Assembly: EdmRelationshipAttribute("Model", "groupeshoraires", "groupes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.groupes), "horaires", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.horaires))>
<Assembly: EdmRelationshipAttribute("Model", "activitesgroupes", "activites", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.activites), "groupes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.groupes))>
<Assembly: EdmRelationshipAttribute("Model", "activitesprealable", "activites", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.activites), "prealable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.prealable))>
<Assembly: EdmRelationshipAttribute("Model", "groupeslisteAttente", "groupes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.groupes), "listeAttente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.listeAttente))>
<Assembly: EdmRelationshipAttribute("Model", "dossiersclients", "dossiers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.dossiers), "clients", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.clients))>
<Assembly: EdmRelationshipAttribute("Model", "clientsinscription", "clients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.clients), "inscription", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.inscription))>
<Assembly: EdmRelationshipAttribute("Model", "clientslisteAttente", "clients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.clients), "listeAttente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.listeAttente))>

#End Region

Namespace Model

    #Region "Contextes"
    
    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    Public Partial Class ModelContainer1
        Inherits ObjectContext
    
        #Region "Constructeurs"
    
        ''' <summary>
        ''' Initialise un nouvel objet ModelContainer1 à l'aide de la chaîne de connexion trouvée dans la section 'ModelContainer1' du fichier de configuration d'application.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=ModelContainer1", "ModelContainer1")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialisez un nouvel objet ModelContainer1.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "ModelContainer1")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialisez un nouvel objet ModelContainer1.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "ModelContainer1")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Méthodes partielles"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Propriétés ObjectSet"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        Public ReadOnly Property groupesJeu() As ObjectSet(Of groupes)
            Get
                If (_groupesJeu Is Nothing) Then
                    _groupesJeu = MyBase.CreateObjectSet(Of groupes)("groupesJeu")
                End If
                Return _groupesJeu
            End Get
        End Property
    
        Private _groupesJeu As ObjectSet(Of groupes)
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        Public ReadOnly Property inscriptionJeu() As ObjectSet(Of inscription)
            Get
                If (_inscriptionJeu Is Nothing) Then
                    _inscriptionJeu = MyBase.CreateObjectSet(Of inscription)("inscriptionJeu")
                End If
                Return _inscriptionJeu
            End Get
        End Property
    
        Private _inscriptionJeu As ObjectSet(Of inscription)
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        Public ReadOnly Property listeAttenteJeu() As ObjectSet(Of listeAttente)
            Get
                If (_listeAttenteJeu Is Nothing) Then
                    _listeAttenteJeu = MyBase.CreateObjectSet(Of listeAttente)("listeAttenteJeu")
                End If
                Return _listeAttenteJeu
            End Get
        End Property
    
        Private _listeAttenteJeu As ObjectSet(Of listeAttente)
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        Public ReadOnly Property paiementsJeu() As ObjectSet(Of paiements)
            Get
                If (_paiementsJeu Is Nothing) Then
                    _paiementsJeu = MyBase.CreateObjectSet(Of paiements)("paiementsJeu")
                End If
                Return _paiementsJeu
            End Get
        End Property
    
        Private _paiementsJeu As ObjectSet(Of paiements)
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        Public ReadOnly Property activitesJeu() As ObjectSet(Of activites)
            Get
                If (_activitesJeu Is Nothing) Then
                    _activitesJeu = MyBase.CreateObjectSet(Of activites)("activitesJeu")
                End If
                Return _activitesJeu
            End Get
        End Property
    
        Private _activitesJeu As ObjectSet(Of activites)
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        Public ReadOnly Property horairesJeu() As ObjectSet(Of horaires)
            Get
                If (_horairesJeu Is Nothing) Then
                    _horairesJeu = MyBase.CreateObjectSet(Of horaires)("horairesJeu")
                End If
                Return _horairesJeu
            End Get
        End Property
    
        Private _horairesJeu As ObjectSet(Of horaires)
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        Public ReadOnly Property prealableJeu() As ObjectSet(Of prealable)
            Get
                If (_prealableJeu Is Nothing) Then
                    _prealableJeu = MyBase.CreateObjectSet(Of prealable)("prealableJeu")
                End If
                Return _prealableJeu
            End Get
        End Property
    
        Private _prealableJeu As ObjectSet(Of prealable)
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        Public ReadOnly Property clientsJeu() As ObjectSet(Of clients)
            Get
                If (_clientsJeu Is Nothing) Then
                    _clientsJeu = MyBase.CreateObjectSet(Of clients)("clientsJeu")
                End If
                Return _clientsJeu
            End Get
        End Property
    
        Private _clientsJeu As ObjectSet(Of clients)
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        Public ReadOnly Property dossiersJeu() As ObjectSet(Of dossiers)
            Get
                If (_dossiersJeu Is Nothing) Then
                    _dossiersJeu = MyBase.CreateObjectSet(Of dossiers)("dossiersJeu")
                End If
                Return _dossiersJeu
            End Get
        End Property
    
        Private _dossiersJeu As ObjectSet(Of dossiers)

        #End Region

        #Region "Méthodes AddTo"
    
        ''' <summary>
        ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet groupesJeu. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
        ''' </summary>
        Public Sub AddTogroupesJeu(ByVal groupes As groupes)
            MyBase.AddObject("groupesJeu", groupes)
        End Sub
    
        ''' <summary>
        ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet inscriptionJeu. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
        ''' </summary>
        Public Sub AddToinscriptionJeu(ByVal inscription As inscription)
            MyBase.AddObject("inscriptionJeu", inscription)
        End Sub
    
        ''' <summary>
        ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet listeAttenteJeu. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
        ''' </summary>
        Public Sub AddTolisteAttenteJeu(ByVal listeAttente As listeAttente)
            MyBase.AddObject("listeAttenteJeu", listeAttente)
        End Sub
    
        ''' <summary>
        ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet paiementsJeu. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
        ''' </summary>
        Public Sub AddTopaiementsJeu(ByVal paiements As paiements)
            MyBase.AddObject("paiementsJeu", paiements)
        End Sub
    
        ''' <summary>
        ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet activitesJeu. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
        ''' </summary>
        Public Sub AddToactivitesJeu(ByVal activites As activites)
            MyBase.AddObject("activitesJeu", activites)
        End Sub
    
        ''' <summary>
        ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet horairesJeu. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
        ''' </summary>
        Public Sub AddTohorairesJeu(ByVal horaires As horaires)
            MyBase.AddObject("horairesJeu", horaires)
        End Sub
    
        ''' <summary>
        ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet prealableJeu. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
        ''' </summary>
        Public Sub AddToprealableJeu(ByVal prealable As prealable)
            MyBase.AddObject("prealableJeu", prealable)
        End Sub
    
        ''' <summary>
        ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet clientsJeu. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
        ''' </summary>
        Public Sub AddToclientsJeu(ByVal clients As clients)
            MyBase.AddObject("clientsJeu", clients)
        End Sub
    
        ''' <summary>
        ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet dossiersJeu. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
        ''' </summary>
        Public Sub AddTodossiersJeu(ByVal dossiers As dossiers)
            MyBase.AddObject("dossiersJeu", dossiers)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entités"
    
    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="activites")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class activites
        Inherits EntityObject
        #Region "Méthode de fabrique"
    
        ''' <summary>
        ''' Créez un nouvel objet activites.
        ''' </summary>
        ''' <param name="noActivite">Valeur initiale de la propriété noActivite.</param>
        ''' <param name="nomActivite">Valeur initiale de la propriété nomActivite.</param>
        ''' <param name="materielRequis">Valeur initiale de la propriété materielRequis.</param>
        ''' <param name="typeActivite">Valeur initiale de la propriété typeActivite.</param>
        ''' <param name="clientele">Valeur initiale de la propriété clientele.</param>
        Public Shared Function Createactivites(noActivite As Global.System.Int32, nomActivite As Global.System.String, materielRequis As Global.System.String, typeActivite As Global.System.String, clientele As Global.System.String) As activites
            Dim activites as activites = New activites
            activites.noActivite = noActivite
            activites.nomActivite = nomActivite
            activites.materielRequis = materielRequis
            activites.typeActivite = typeActivite
            activites.clientele = clientele
            Return activites
        End Function

        #End Region

        #Region "Propriétés primitives"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noActivite() As Global.System.Int32
            Get
                Return _noActivite
            End Get
            Set
                If (_noActivite <> Value) Then
                    OnnoActiviteChanging(value)
                    ReportPropertyChanging("noActivite")
                    _noActivite = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("noActivite")
                    OnnoActiviteChanged()
                End If
            End Set
        End Property
    
        Private _noActivite As Global.System.Int32
        Private Partial Sub OnnoActiviteChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoActiviteChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property nomActivite() As Global.System.String
            Get
                Return _nomActivite
            End Get
            Set
                OnnomActiviteChanging(value)
                ReportPropertyChanging("nomActivite")
                _nomActivite = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("nomActivite")
                OnnomActiviteChanged()
            End Set
        End Property
    
        Private _nomActivite As Global.System.String
        Private Partial Sub OnnomActiviteChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnomActiviteChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property materielRequis() As Global.System.String
            Get
                Return _materielRequis
            End Get
            Set
                OnmaterielRequisChanging(value)
                ReportPropertyChanging("materielRequis")
                _materielRequis = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("materielRequis")
                OnmaterielRequisChanged()
            End Set
        End Property
    
        Private _materielRequis As Global.System.String
        Private Partial Sub OnmaterielRequisChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnmaterielRequisChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property typeActivite() As Global.System.String
            Get
                Return _typeActivite
            End Get
            Set
                OntypeActiviteChanging(value)
                ReportPropertyChanging("typeActivite")
                _typeActivite = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("typeActivite")
                OntypeActiviteChanged()
            End Set
        End Property
    
        Private _typeActivite As Global.System.String
        Private Partial Sub OntypeActiviteChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OntypeActiviteChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property clientele() As Global.System.String
            Get
                Return _clientele
            End Get
            Set
                OnclienteleChanging(value)
                ReportPropertyChanging("clientele")
                _clientele = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("clientele")
                OnclienteleChanged()
            End Set
        End Property
    
        Private _clientele As Global.System.String
        Private Partial Sub OnclienteleChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnclienteleChanged()
        End Sub

        #End Region

        #Region "Propriétés de navigation"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "activitesgroupes", "groupes")>
         Public Property groupes() As EntityCollection(Of groupes)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of groupes)("Model.activitesgroupes", "groupes")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of groupes)("Model.activitesgroupes", "groupes", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "activitesprealable", "prealable")>
         Public Property prealable() As EntityCollection(Of prealable)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of prealable)("Model.activitesprealable", "prealable")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of prealable)("Model.activitesprealable", "prealable", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="clients")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class clients
        Inherits EntityObject
        #Region "Méthode de fabrique"
    
        ''' <summary>
        ''' Créez un nouvel objet clients.
        ''' </summary>
        ''' <param name="noClient">Valeur initiale de la propriété noClient.</param>
        ''' <param name="noDossier">Valeur initiale de la propriété noDossier.</param>
        ''' <param name="nom">Valeur initiale de la propriété nom.</param>
        ''' <param name="prenom">Valeur initiale de la propriété prenom.</param>
        ''' <param name="dateNaissance">Valeur initiale de la propriété dateNaissance.</param>
        Public Shared Function Createclients(noClient As Global.System.Int32, noDossier As Global.System.String, nom As Global.System.String, prenom As Global.System.String, dateNaissance As Global.System.String) As clients
            Dim clients as clients = New clients
            clients.noClient = noClient
            clients.noDossier = noDossier
            clients.nom = nom
            clients.prenom = prenom
            clients.dateNaissance = dateNaissance
            Return clients
        End Function

        #End Region

        #Region "Propriétés primitives"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noClient() As Global.System.Int32
            Get
                Return _noClient
            End Get
            Set
                If (_noClient <> Value) Then
                    OnnoClientChanging(value)
                    ReportPropertyChanging("noClient")
                    _noClient = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("noClient")
                    OnnoClientChanged()
                End If
            End Set
        End Property
    
        Private _noClient As Global.System.Int32
        Private Partial Sub OnnoClientChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoClientChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noDossier() As Global.System.String
            Get
                Return _noDossier
            End Get
            Set
                OnnoDossierChanging(value)
                ReportPropertyChanging("noDossier")
                _noDossier = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("noDossier")
                OnnoDossierChanged()
            End Set
        End Property
    
        Private _noDossier As Global.System.String
        Private Partial Sub OnnoDossierChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnoDossierChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property nom() As Global.System.String
            Get
                Return _nom
            End Get
            Set
                OnnomChanging(value)
                ReportPropertyChanging("nom")
                _nom = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("nom")
                OnnomChanged()
            End Set
        End Property
    
        Private _nom As Global.System.String
        Private Partial Sub OnnomChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnomChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property prenom() As Global.System.String
            Get
                Return _prenom
            End Get
            Set
                OnprenomChanging(value)
                ReportPropertyChanging("prenom")
                _prenom = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("prenom")
                OnprenomChanged()
            End Set
        End Property
    
        Private _prenom As Global.System.String
        Private Partial Sub OnprenomChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnprenomChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property dateNaissance() As Global.System.String
            Get
                Return _dateNaissance
            End Get
            Set
                OndateNaissanceChanging(value)
                ReportPropertyChanging("dateNaissance")
                _dateNaissance = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("dateNaissance")
                OndateNaissanceChanged()
            End Set
        End Property
    
        Private _dateNaissance As Global.System.String
        Private Partial Sub OndateNaissanceChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OndateNaissanceChanged()
        End Sub

        #End Region

        #Region "Propriétés de navigation"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "dossiersclients", "dossiers")>
        Public Property dossiers() As dossiers
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of dossiers)("Model.dossiersclients", "dossiers").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of dossiers)("Model.dossiersclients", "dossiers").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property dossiersReference() As EntityReference(Of dossiers)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of dossiers)("Model.dossiersclients", "dossiers")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of dossiers)("Model.dossiersclients", "dossiers", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "clientsinscription", "inscription")>
         Public Property inscription() As EntityCollection(Of inscription)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of inscription)("Model.clientsinscription", "inscription")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of inscription)("Model.clientsinscription", "inscription", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "clientslisteAttente", "listeAttente")>
         Public Property listeAttente() As EntityCollection(Of listeAttente)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of listeAttente)("Model.clientslisteAttente", "listeAttente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of listeAttente)("Model.clientslisteAttente", "listeAttente", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="dossiers")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class dossiers
        Inherits EntityObject
        #Region "Méthode de fabrique"
    
        ''' <summary>
        ''' Créez un nouvel objet dossiers.
        ''' </summary>
        ''' <param name="noDossier">Valeur initiale de la propriété noDossier.</param>
        ''' <param name="adresse">Valeur initiale de la propriété adresse.</param>
        ''' <param name="ville">Valeur initiale de la propriété ville.</param>
        ''' <param name="codePostal">Valeur initiale de la propriété codePostal.</param>
        ''' <param name="province">Valeur initiale de la propriété province.</param>
        ''' <param name="noTelephone">Valeur initiale de la propriété noTelephone.</param>
        ''' <param name="email">Valeur initiale de la propriété email.</param>
        ''' <param name="username">Valeur initiale de la propriété username.</param>
        ''' <param name="password">Valeur initiale de la propriété password.</param>
        ''' <param name="typeUtilisateur">Valeur initiale de la propriété typeUtilisateur.</param>
        Public Shared Function Createdossiers(noDossier As Global.System.Int32, adresse As Global.System.String, ville As Global.System.String, codePostal As Global.System.String, province As Global.System.String, noTelephone As Global.System.String, email As Global.System.String, username As Global.System.String, password As Global.System.String, typeUtilisateur As Global.System.String) As dossiers
            Dim dossiers as dossiers = New dossiers
            dossiers.noDossier = noDossier
            dossiers.adresse = adresse
            dossiers.ville = ville
            dossiers.codePostal = codePostal
            dossiers.province = province
            dossiers.noTelephone = noTelephone
            dossiers.email = email
            dossiers.username = username
            dossiers.password = password
            dossiers.typeUtilisateur = typeUtilisateur
            Return dossiers
        End Function

        #End Region

        #Region "Propriétés primitives"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noDossier() As Global.System.Int32
            Get
                Return _noDossier
            End Get
            Set
                If (_noDossier <> Value) Then
                    OnnoDossierChanging(value)
                    ReportPropertyChanging("noDossier")
                    _noDossier = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("noDossier")
                    OnnoDossierChanged()
                End If
            End Set
        End Property
    
        Private _noDossier As Global.System.Int32
        Private Partial Sub OnnoDossierChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoDossierChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property adresse() As Global.System.String
            Get
                Return _adresse
            End Get
            Set
                OnadresseChanging(value)
                ReportPropertyChanging("adresse")
                _adresse = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("adresse")
                OnadresseChanged()
            End Set
        End Property
    
        Private _adresse As Global.System.String
        Private Partial Sub OnadresseChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnadresseChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ville() As Global.System.String
            Get
                Return _ville
            End Get
            Set
                OnvilleChanging(value)
                ReportPropertyChanging("ville")
                _ville = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ville")
                OnvilleChanged()
            End Set
        End Property
    
        Private _ville As Global.System.String
        Private Partial Sub OnvilleChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnvilleChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property codePostal() As Global.System.String
            Get
                Return _codePostal
            End Get
            Set
                OncodePostalChanging(value)
                ReportPropertyChanging("codePostal")
                _codePostal = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("codePostal")
                OncodePostalChanged()
            End Set
        End Property
    
        Private _codePostal As Global.System.String
        Private Partial Sub OncodePostalChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OncodePostalChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property province() As Global.System.String
            Get
                Return _province
            End Get
            Set
                OnprovinceChanging(value)
                ReportPropertyChanging("province")
                _province = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("province")
                OnprovinceChanged()
            End Set
        End Property
    
        Private _province As Global.System.String
        Private Partial Sub OnprovinceChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnprovinceChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noTelephone() As Global.System.String
            Get
                Return _noTelephone
            End Get
            Set
                OnnoTelephoneChanging(value)
                ReportPropertyChanging("noTelephone")
                _noTelephone = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("noTelephone")
                OnnoTelephoneChanged()
            End Set
        End Property
    
        Private _noTelephone As Global.System.String
        Private Partial Sub OnnoTelephoneChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnoTelephoneChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property email() As Global.System.String
            Get
                Return _email
            End Get
            Set
                OnemailChanging(value)
                ReportPropertyChanging("email")
                _email = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("email")
                OnemailChanged()
            End Set
        End Property
    
        Private _email As Global.System.String
        Private Partial Sub OnemailChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnemailChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property username() As Global.System.String
            Get
                Return _username
            End Get
            Set
                OnusernameChanging(value)
                ReportPropertyChanging("username")
                _username = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("username")
                OnusernameChanged()
            End Set
        End Property
    
        Private _username As Global.System.String
        Private Partial Sub OnusernameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnusernameChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property password() As Global.System.String
            Get
                Return _password
            End Get
            Set
                OnpasswordChanging(value)
                ReportPropertyChanging("password")
                _password = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("password")
                OnpasswordChanged()
            End Set
        End Property
    
        Private _password As Global.System.String
        Private Partial Sub OnpasswordChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnpasswordChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property typeUtilisateur() As Global.System.String
            Get
                Return _typeUtilisateur
            End Get
            Set
                OntypeUtilisateurChanging(value)
                ReportPropertyChanging("typeUtilisateur")
                _typeUtilisateur = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("typeUtilisateur")
                OntypeUtilisateurChanged()
            End Set
        End Property
    
        Private _typeUtilisateur As Global.System.String
        Private Partial Sub OntypeUtilisateurChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OntypeUtilisateurChanged()
        End Sub

        #End Region

        #Region "Propriétés de navigation"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "dossiersclients", "clients")>
         Public Property clients() As EntityCollection(Of clients)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of clients)("Model.dossiersclients", "clients")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of clients)("Model.dossiersclients", "clients", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="groupes")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class groupes
        Inherits EntityObject
        #Region "Méthode de fabrique"
    
        ''' <summary>
        ''' Créez un nouvel objet groupes.
        ''' </summary>
        ''' <param name="noGroupe">Valeur initiale de la propriété noGroupe.</param>
        ''' <param name="nomProf">Valeur initiale de la propriété nomProf.</param>
        ''' <param name="prix">Valeur initiale de la propriété prix.</param>
        ''' <param name="nbPlaceDisponible">Valeur initiale de la propriété nbPlaceDisponible.</param>
        ''' <param name="ageMin">Valeur initiale de la propriété ageMin.</param>
        ''' <param name="ageMax">Valeur initiale de la propriété ageMax.</param>
        ''' <param name="session">Valeur initiale de la propriété session.</param>
        ''' <param name="dateDebut">Valeur initiale de la propriété dateDebut.</param>
        ''' <param name="noActivite">Valeur initiale de la propriété noActivite.</param>
        Public Shared Function Creategroupes(noGroupe As Global.System.Int32, nomProf As Global.System.String, prix As Global.System.Int32, nbPlaceDisponible As Global.System.String, ageMin As Global.System.Int32, ageMax As Global.System.Int32, session As Global.System.String, dateDebut As Global.System.String, noActivite As Global.System.String) As groupes
            Dim groupes as groupes = New groupes
            groupes.noGroupe = noGroupe
            groupes.nomProf = nomProf
            groupes.prix = prix
            groupes.nbPlaceDisponible = nbPlaceDisponible
            groupes.ageMin = ageMin
            groupes.ageMax = ageMax
            groupes.session = session
            groupes.dateDebut = dateDebut
            groupes.noActivite = noActivite
            Return groupes
        End Function

        #End Region

        #Region "Propriétés primitives"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noGroupe() As Global.System.Int32
            Get
                Return _noGroupe
            End Get
            Set
                If (_noGroupe <> Value) Then
                    OnnoGroupeChanging(value)
                    ReportPropertyChanging("noGroupe")
                    _noGroupe = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("noGroupe")
                    OnnoGroupeChanged()
                End If
            End Set
        End Property
    
        Private _noGroupe As Global.System.Int32
        Private Partial Sub OnnoGroupeChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoGroupeChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property nomProf() As Global.System.String
            Get
                Return _nomProf
            End Get
            Set
                OnnomProfChanging(value)
                ReportPropertyChanging("nomProf")
                _nomProf = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("nomProf")
                OnnomProfChanged()
            End Set
        End Property
    
        Private _nomProf As Global.System.String
        Private Partial Sub OnnomProfChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnomProfChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property prix() As Global.System.Int32
            Get
                Return _prix
            End Get
            Set
                OnprixChanging(value)
                ReportPropertyChanging("prix")
                _prix = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("prix")
                OnprixChanged()
            End Set
        End Property
    
        Private _prix As Global.System.Int32
        Private Partial Sub OnprixChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnprixChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property nbPlaceDisponible() As Global.System.String
            Get
                Return _nbPlaceDisponible
            End Get
            Set
                OnnbPlaceDisponibleChanging(value)
                ReportPropertyChanging("nbPlaceDisponible")
                _nbPlaceDisponible = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("nbPlaceDisponible")
                OnnbPlaceDisponibleChanged()
            End Set
        End Property
    
        Private _nbPlaceDisponible As Global.System.String
        Private Partial Sub OnnbPlaceDisponibleChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnbPlaceDisponibleChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ageMin() As Global.System.Int32
            Get
                Return _ageMin
            End Get
            Set
                OnageMinChanging(value)
                ReportPropertyChanging("ageMin")
                _ageMin = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ageMin")
                OnageMinChanged()
            End Set
        End Property
    
        Private _ageMin As Global.System.Int32
        Private Partial Sub OnageMinChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnageMinChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ageMax() As Global.System.Int32
            Get
                Return _ageMax
            End Get
            Set
                OnageMaxChanging(value)
                ReportPropertyChanging("ageMax")
                _ageMax = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ageMax")
                OnageMaxChanged()
            End Set
        End Property
    
        Private _ageMax As Global.System.Int32
        Private Partial Sub OnageMaxChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnageMaxChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property session() As Global.System.String
            Get
                Return _session
            End Get
            Set
                OnsessionChanging(value)
                ReportPropertyChanging("session")
                _session = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("session")
                OnsessionChanged()
            End Set
        End Property
    
        Private _session As Global.System.String
        Private Partial Sub OnsessionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnsessionChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property dateDebut() As Global.System.String
            Get
                Return _dateDebut
            End Get
            Set
                OndateDebutChanging(value)
                ReportPropertyChanging("dateDebut")
                _dateDebut = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("dateDebut")
                OndateDebutChanged()
            End Set
        End Property
    
        Private _dateDebut As Global.System.String
        Private Partial Sub OndateDebutChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OndateDebutChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noActivite() As Global.System.String
            Get
                Return _noActivite
            End Get
            Set
                OnnoActiviteChanging(value)
                ReportPropertyChanging("noActivite")
                _noActivite = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("noActivite")
                OnnoActiviteChanged()
            End Set
        End Property
    
        Private _noActivite As Global.System.String
        Private Partial Sub OnnoActiviteChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnoActiviteChanged()
        End Sub

        #End Region

        #Region "Propriétés de navigation"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "groupesinscription", "inscription")>
         Public Property inscription() As EntityCollection(Of inscription)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of inscription)("Model.groupesinscription", "inscription")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of inscription)("Model.groupesinscription", "inscription", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "groupeshoraires", "horaires")>
         Public Property horaires() As EntityCollection(Of horaires)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of horaires)("Model.groupeshoraires", "horaires")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of horaires)("Model.groupeshoraires", "horaires", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "activitesgroupes", "activites")>
        Public Property activites() As activites
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of activites)("Model.activitesgroupes", "activites").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of activites)("Model.activitesgroupes", "activites").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property activitesReference() As EntityReference(Of activites)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of activites)("Model.activitesgroupes", "activites")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of activites)("Model.activitesgroupes", "activites", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "groupeslisteAttente", "listeAttente")>
         Public Property listeAttente() As EntityCollection(Of listeAttente)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of listeAttente)("Model.groupeslisteAttente", "listeAttente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of listeAttente)("Model.groupeslisteAttente", "listeAttente", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="horaires")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class horaires
        Inherits EntityObject
        #Region "Méthode de fabrique"
    
        ''' <summary>
        ''' Créez un nouvel objet horaires.
        ''' </summary>
        ''' <param name="noHoraire">Valeur initiale de la propriété noHoraire.</param>
        ''' <param name="noGroupe">Valeur initiale de la propriété noGroupe.</param>
        ''' <param name="heureDebut">Valeur initiale de la propriété heureDebut.</param>
        ''' <param name="heureFin">Valeur initiale de la propriété heureFin.</param>
        ''' <param name="emplacement">Valeur initiale de la propriété emplacement.</param>
        Public Shared Function Createhoraires(noHoraire As Global.System.Int32, noGroupe As Global.System.String, heureDebut As Global.System.String, heureFin As Global.System.String, emplacement As Global.System.String) As horaires
            Dim horaires as horaires = New horaires
            horaires.noHoraire = noHoraire
            horaires.noGroupe = noGroupe
            horaires.heureDebut = heureDebut
            horaires.heureFin = heureFin
            horaires.emplacement = emplacement
            Return horaires
        End Function

        #End Region

        #Region "Propriétés primitives"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noHoraire() As Global.System.Int32
            Get
                Return _noHoraire
            End Get
            Set
                If (_noHoraire <> Value) Then
                    OnnoHoraireChanging(value)
                    ReportPropertyChanging("noHoraire")
                    _noHoraire = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("noHoraire")
                    OnnoHoraireChanged()
                End If
            End Set
        End Property
    
        Private _noHoraire As Global.System.Int32
        Private Partial Sub OnnoHoraireChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoHoraireChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noGroupe() As Global.System.String
            Get
                Return _noGroupe
            End Get
            Set
                OnnoGroupeChanging(value)
                ReportPropertyChanging("noGroupe")
                _noGroupe = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("noGroupe")
                OnnoGroupeChanged()
            End Set
        End Property
    
        Private _noGroupe As Global.System.String
        Private Partial Sub OnnoGroupeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnoGroupeChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property heureDebut() As Global.System.String
            Get
                Return _heureDebut
            End Get
            Set
                OnheureDebutChanging(value)
                ReportPropertyChanging("heureDebut")
                _heureDebut = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("heureDebut")
                OnheureDebutChanged()
            End Set
        End Property
    
        Private _heureDebut As Global.System.String
        Private Partial Sub OnheureDebutChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnheureDebutChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property heureFin() As Global.System.String
            Get
                Return _heureFin
            End Get
            Set
                OnheureFinChanging(value)
                ReportPropertyChanging("heureFin")
                _heureFin = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("heureFin")
                OnheureFinChanged()
            End Set
        End Property
    
        Private _heureFin As Global.System.String
        Private Partial Sub OnheureFinChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnheureFinChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property emplacement() As Global.System.String
            Get
                Return _emplacement
            End Get
            Set
                OnemplacementChanging(value)
                ReportPropertyChanging("emplacement")
                _emplacement = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("emplacement")
                OnemplacementChanged()
            End Set
        End Property
    
        Private _emplacement As Global.System.String
        Private Partial Sub OnemplacementChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnemplacementChanged()
        End Sub

        #End Region

        #Region "Propriétés de navigation"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "groupeshoraires", "groupes")>
        Public Property groupes() As groupes
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of groupes)("Model.groupeshoraires", "groupes").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of groupes)("Model.groupeshoraires", "groupes").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property groupesReference() As EntityReference(Of groupes)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of groupes)("Model.groupeshoraires", "groupes")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of groupes)("Model.groupeshoraires", "groupes", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="inscription")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class inscription
        Inherits EntityObject
        #Region "Méthode de fabrique"
    
        ''' <summary>
        ''' Créez un nouvel objet inscription.
        ''' </summary>
        ''' <param name="noInscription">Valeur initiale de la propriété noInscription.</param>
        ''' <param name="noClient">Valeur initiale de la propriété noClient.</param>
        ''' <param name="dateInscription">Valeur initiale de la propriété dateInscription.</param>
        ''' <param name="descriptionAchat">Valeur initiale de la propriété descriptionAchat.</param>
        ''' <param name="noGroupe">Valeur initiale de la propriété noGroupe.</param>
        ''' <param name="noPaiement">Valeur initiale de la propriété noPaiement.</param>
        Public Shared Function Createinscription(noInscription As Global.System.Int32, noClient As Global.System.String, dateInscription As Global.System.String, descriptionAchat As Global.System.String, noGroupe As Global.System.String, noPaiement As Global.System.String) As inscription
            Dim inscription as inscription = New inscription
            inscription.noInscription = noInscription
            inscription.noClient = noClient
            inscription.dateInscription = dateInscription
            inscription.descriptionAchat = descriptionAchat
            inscription.noGroupe = noGroupe
            inscription.noPaiement = noPaiement
            Return inscription
        End Function

        #End Region

        #Region "Propriétés primitives"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noInscription() As Global.System.Int32
            Get
                Return _noInscription
            End Get
            Set
                If (_noInscription <> Value) Then
                    OnnoInscriptionChanging(value)
                    ReportPropertyChanging("noInscription")
                    _noInscription = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("noInscription")
                    OnnoInscriptionChanged()
                End If
            End Set
        End Property
    
        Private _noInscription As Global.System.Int32
        Private Partial Sub OnnoInscriptionChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoInscriptionChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noClient() As Global.System.String
            Get
                Return _noClient
            End Get
            Set
                OnnoClientChanging(value)
                ReportPropertyChanging("noClient")
                _noClient = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("noClient")
                OnnoClientChanged()
            End Set
        End Property
    
        Private _noClient As Global.System.String
        Private Partial Sub OnnoClientChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnoClientChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property dateInscription() As Global.System.String
            Get
                Return _dateInscription
            End Get
            Set
                OndateInscriptionChanging(value)
                ReportPropertyChanging("dateInscription")
                _dateInscription = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("dateInscription")
                OndateInscriptionChanged()
            End Set
        End Property
    
        Private _dateInscription As Global.System.String
        Private Partial Sub OndateInscriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OndateInscriptionChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property descriptionAchat() As Global.System.String
            Get
                Return _descriptionAchat
            End Get
            Set
                OndescriptionAchatChanging(value)
                ReportPropertyChanging("descriptionAchat")
                _descriptionAchat = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("descriptionAchat")
                OndescriptionAchatChanged()
            End Set
        End Property
    
        Private _descriptionAchat As Global.System.String
        Private Partial Sub OndescriptionAchatChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OndescriptionAchatChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noGroupe() As Global.System.String
            Get
                Return _noGroupe
            End Get
            Set
                OnnoGroupeChanging(value)
                ReportPropertyChanging("noGroupe")
                _noGroupe = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("noGroupe")
                OnnoGroupeChanged()
            End Set
        End Property
    
        Private _noGroupe As Global.System.String
        Private Partial Sub OnnoGroupeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnoGroupeChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noPaiement() As Global.System.String
            Get
                Return _noPaiement
            End Get
            Set
                OnnoPaiementChanging(value)
                ReportPropertyChanging("noPaiement")
                _noPaiement = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("noPaiement")
                OnnoPaiementChanged()
            End Set
        End Property
    
        Private _noPaiement As Global.System.String
        Private Partial Sub OnnoPaiementChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnoPaiementChanged()
        End Sub

        #End Region

        #Region "Propriétés de navigation"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "groupesinscription", "groupes")>
        Public Property groupes() As groupes
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of groupes)("Model.groupesinscription", "groupes").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of groupes)("Model.groupesinscription", "groupes").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property groupesReference() As EntityReference(Of groupes)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of groupes)("Model.groupesinscription", "groupes")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of groupes)("Model.groupesinscription", "groupes", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "paiementsinscription", "paiements")>
        Public Property paiements() As paiements
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of paiements)("Model.paiementsinscription", "paiements").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of paiements)("Model.paiementsinscription", "paiements").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property paiementsReference() As EntityReference(Of paiements)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of paiements)("Model.paiementsinscription", "paiements")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of paiements)("Model.paiementsinscription", "paiements", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "clientsinscription", "clients")>
        Public Property clients() As clients
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of clients)("Model.clientsinscription", "clients").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of clients)("Model.clientsinscription", "clients").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property clientsReference() As EntityReference(Of clients)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of clients)("Model.clientsinscription", "clients")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of clients)("Model.clientsinscription", "clients", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="listeAttente")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class listeAttente
        Inherits EntityObject
        #Region "Méthode de fabrique"
    
        ''' <summary>
        ''' Créez un nouvel objet listeAttente.
        ''' </summary>
        ''' <param name="noListeAttente">Valeur initiale de la propriété noListeAttente.</param>
        ''' <param name="noGroupe">Valeur initiale de la propriété noGroupe.</param>
        ''' <param name="noClient">Valeur initiale de la propriété noClient.</param>
        ''' <param name="dateDebutAttente">Valeur initiale de la propriété dateDebutAttente.</param>
        Public Shared Function CreatelisteAttente(noListeAttente As Global.System.Int32, noGroupe As Global.System.Int32, noClient As Global.System.String, dateDebutAttente As Global.System.String) As listeAttente
            Dim listeAttente as listeAttente = New listeAttente
            listeAttente.noListeAttente = noListeAttente
            listeAttente.noGroupe = noGroupe
            listeAttente.noClient = noClient
            listeAttente.dateDebutAttente = dateDebutAttente
            Return listeAttente
        End Function

        #End Region

        #Region "Propriétés primitives"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noListeAttente() As Global.System.Int32
            Get
                Return _noListeAttente
            End Get
            Set
                If (_noListeAttente <> Value) Then
                    OnnoListeAttenteChanging(value)
                    ReportPropertyChanging("noListeAttente")
                    _noListeAttente = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("noListeAttente")
                    OnnoListeAttenteChanged()
                End If
            End Set
        End Property
    
        Private _noListeAttente As Global.System.Int32
        Private Partial Sub OnnoListeAttenteChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoListeAttenteChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noGroupe() As Global.System.Int32
            Get
                Return _noGroupe
            End Get
            Set
                OnnoGroupeChanging(value)
                ReportPropertyChanging("noGroupe")
                _noGroupe = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("noGroupe")
                OnnoGroupeChanged()
            End Set
        End Property
    
        Private _noGroupe As Global.System.Int32
        Private Partial Sub OnnoGroupeChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoGroupeChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noClient() As Global.System.String
            Get
                Return _noClient
            End Get
            Set
                OnnoClientChanging(value)
                ReportPropertyChanging("noClient")
                _noClient = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("noClient")
                OnnoClientChanged()
            End Set
        End Property
    
        Private _noClient As Global.System.String
        Private Partial Sub OnnoClientChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnoClientChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property dateDebutAttente() As Global.System.String
            Get
                Return _dateDebutAttente
            End Get
            Set
                OndateDebutAttenteChanging(value)
                ReportPropertyChanging("dateDebutAttente")
                _dateDebutAttente = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("dateDebutAttente")
                OndateDebutAttenteChanged()
            End Set
        End Property
    
        Private _dateDebutAttente As Global.System.String
        Private Partial Sub OndateDebutAttenteChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OndateDebutAttenteChanged()
        End Sub

        #End Region

        #Region "Propriétés de navigation"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "groupeslisteAttente", "groupes")>
        Public Property groupes() As groupes
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of groupes)("Model.groupeslisteAttente", "groupes").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of groupes)("Model.groupeslisteAttente", "groupes").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property groupesReference() As EntityReference(Of groupes)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of groupes)("Model.groupeslisteAttente", "groupes")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of groupes)("Model.groupeslisteAttente", "groupes", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "clientslisteAttente", "clients")>
        Public Property clients() As clients
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of clients)("Model.clientslisteAttente", "clients").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of clients)("Model.clientslisteAttente", "clients").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property clientsReference() As EntityReference(Of clients)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of clients)("Model.clientslisteAttente", "clients")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of clients)("Model.clientslisteAttente", "clients", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="paiements")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class paiements
        Inherits EntityObject
        #Region "Méthode de fabrique"
    
        ''' <summary>
        ''' Créez un nouvel objet paiements.
        ''' </summary>
        ''' <param name="noPaiement">Valeur initiale de la propriété noPaiement.</param>
        ''' <param name="noInscription">Valeur initiale de la propriété noInscription.</param>
        ''' <param name="datePaiement">Valeur initiale de la propriété datePaiement.</param>
        ''' <param name="tPS">Valeur initiale de la propriété TPS.</param>
        ''' <param name="tVQ">Valeur initiale de la propriété TVQ.</param>
        ''' <param name="rabais">Valeur initiale de la propriété rabais.</param>
        ''' <param name="totalPaiement">Valeur initiale de la propriété totalPaiement.</param>
        Public Shared Function Createpaiements(noPaiement As Global.System.Int32, noInscription As Global.System.String, datePaiement As Global.System.String, tPS As Global.System.Int32, tVQ As Global.System.Int32, rabais As Global.System.String, totalPaiement As Global.System.String) As paiements
            Dim paiements as paiements = New paiements
            paiements.noPaiement = noPaiement
            paiements.noInscription = noInscription
            paiements.datePaiement = datePaiement
            paiements.TPS = tPS
            paiements.TVQ = tVQ
            paiements.rabais = rabais
            paiements.totalPaiement = totalPaiement
            Return paiements
        End Function

        #End Region

        #Region "Propriétés primitives"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noPaiement() As Global.System.Int32
            Get
                Return _noPaiement
            End Get
            Set
                If (_noPaiement <> Value) Then
                    OnnoPaiementChanging(value)
                    ReportPropertyChanging("noPaiement")
                    _noPaiement = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("noPaiement")
                    OnnoPaiementChanged()
                End If
            End Set
        End Property
    
        Private _noPaiement As Global.System.Int32
        Private Partial Sub OnnoPaiementChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoPaiementChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noInscription() As Global.System.String
            Get
                Return _noInscription
            End Get
            Set
                OnnoInscriptionChanging(value)
                ReportPropertyChanging("noInscription")
                _noInscription = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("noInscription")
                OnnoInscriptionChanged()
            End Set
        End Property
    
        Private _noInscription As Global.System.String
        Private Partial Sub OnnoInscriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnoInscriptionChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property datePaiement() As Global.System.String
            Get
                Return _datePaiement
            End Get
            Set
                OndatePaiementChanging(value)
                ReportPropertyChanging("datePaiement")
                _datePaiement = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("datePaiement")
                OndatePaiementChanged()
            End Set
        End Property
    
        Private _datePaiement As Global.System.String
        Private Partial Sub OndatePaiementChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OndatePaiementChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property TPS() As Global.System.Int32
            Get
                Return _TPS
            End Get
            Set
                OnTPSChanging(value)
                ReportPropertyChanging("TPS")
                _TPS = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("TPS")
                OnTPSChanged()
            End Set
        End Property
    
        Private _TPS As Global.System.Int32
        Private Partial Sub OnTPSChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnTPSChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property TVQ() As Global.System.Int32
            Get
                Return _TVQ
            End Get
            Set
                OnTVQChanging(value)
                ReportPropertyChanging("TVQ")
                _TVQ = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("TVQ")
                OnTVQChanged()
            End Set
        End Property
    
        Private _TVQ As Global.System.Int32
        Private Partial Sub OnTVQChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnTVQChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property rabais() As Global.System.String
            Get
                Return _rabais
            End Get
            Set
                OnrabaisChanging(value)
                ReportPropertyChanging("rabais")
                _rabais = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("rabais")
                OnrabaisChanged()
            End Set
        End Property
    
        Private _rabais As Global.System.String
        Private Partial Sub OnrabaisChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnrabaisChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property totalPaiement() As Global.System.String
            Get
                Return _totalPaiement
            End Get
            Set
                OntotalPaiementChanging(value)
                ReportPropertyChanging("totalPaiement")
                _totalPaiement = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("totalPaiement")
                OntotalPaiementChanged()
            End Set
        End Property
    
        Private _totalPaiement As Global.System.String
        Private Partial Sub OntotalPaiementChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OntotalPaiementChanged()
        End Sub

        #End Region

        #Region "Propriétés de navigation"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "paiementsinscription", "inscription")>
         Public Property inscription() As EntityCollection(Of inscription)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of inscription)("Model.paiementsinscription", "inscription")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of inscription)("Model.paiementsinscription", "inscription", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="prealable")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class prealable
        Inherits EntityObject
        #Region "Méthode de fabrique"
    
        ''' <summary>
        ''' Créez un nouvel objet prealable.
        ''' </summary>
        ''' <param name="noPrealable">Valeur initiale de la propriété noPrealable.</param>
        ''' <param name="description">Valeur initiale de la propriété description.</param>
        ''' <param name="noActivite">Valeur initiale de la propriété noActivite.</param>
        Public Shared Function Createprealable(noPrealable As Global.System.Int32, description As Global.System.String, noActivite As Global.System.String) As prealable
            Dim prealable as prealable = New prealable
            prealable.noPrealable = noPrealable
            prealable.description = description
            prealable.noActivite = noActivite
            Return prealable
        End Function

        #End Region

        #Region "Propriétés primitives"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noPrealable() As Global.System.Int32
            Get
                Return _noPrealable
            End Get
            Set
                If (_noPrealable <> Value) Then
                    OnnoPrealableChanging(value)
                    ReportPropertyChanging("noPrealable")
                    _noPrealable = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("noPrealable")
                    OnnoPrealableChanged()
                End If
            End Set
        End Property
    
        Private _noPrealable As Global.System.Int32
        Private Partial Sub OnnoPrealableChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoPrealableChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property description() As Global.System.String
            Get
                Return _description
            End Get
            Set
                OndescriptionChanging(value)
                ReportPropertyChanging("description")
                _description = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("description")
                OndescriptionChanged()
            End Set
        End Property
    
        Private _description As Global.System.String
        Private Partial Sub OndescriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OndescriptionChanged()
        End Sub
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noActivite() As Global.System.String
            Get
                Return _noActivite
            End Get
            Set
                OnnoActiviteChanging(value)
                ReportPropertyChanging("noActivite")
                _noActivite = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("noActivite")
                OnnoActiviteChanged()
            End Set
        End Property
    
        Private _noActivite As Global.System.String
        Private Partial Sub OnnoActiviteChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnoActiviteChanged()
        End Sub

        #End Region

        #Region "Propriétés de navigation"
    
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "activitesprealable", "activites")>
        Public Property activites() As activites
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of activites)("Model.activitesprealable", "activites").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of activites)("Model.activitesprealable", "activites").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Aucune documentation sur les métadonnées n'est disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property activitesReference() As EntityReference(Of activites)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of activites)("Model.activitesprealable", "activites")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of activites)("Model.activitesprealable", "activites", value)
                End If
            End Set
        End Property

        #End Region

    End Class

    #End Region

    
End Namespace
